### ISSUE TITLE
Compliance with GPLv3 License

### ISSUE THREAD

**Issue by slm4996** [bwya77/o365_Admin_Center#7]
Where do you make your source available? Since this project is listed as GPLv3 licensing and you publish this project to the public you must also make available the source code.

**Comment by bwya77** [comment]
It's no longer GPLv3 or open sourced. It has its own licensing EULA and this GitHub is no longer updated

**Comment by slm4996** [comment]
GPL is a copyleft license. All derivative works are automatically GPL. You did a complete from scratch rewrite of your project?

**Comment by bwya77** [comment]
Yes, v3 (the code that is still publicly available) is not the same as 'v4'
v4 was made from an entirely new project from scratch. v3 code remains open to the public and the old v3 is free to use.

**Comment by chrisbrownie** [comment]
Do you expect anyone to buy that you actually rewrote the whole thing from scratch? The GUIs are identical.

**Comment by bwya77** [comment]
The UIs were saved as form templates before the project was even made open source. The UIs are created in PoSH Studio as well and not hard coded. 

Along with that v4 added over 18 **new** UI child forms. Every single child form was also removed and re-written without any templates due to a formatting issue with v3. Each script-block for every item was also re-done from scratch due to flagging NULL values, adding form cursor when working to when complete, changing tenant commands, and advanced logging. v4 also has ~10,000 more lines of code that v3 had. This was much easier to do by starting the project over. 

This is the main reason v3 to v4 took ~6 months.
